#############################################################################
# Generated by PAGE version 5.0.2
#  in conjunction with Tcl version 8.6
#  Mar 05, 2020 03:50:11 PM CST  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {DejaVu Sans Mono} -size 9"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {DejaVu Sans} -size 9"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set desc "-family {Liberation Sans} -size 9 -weight bold"
set vTcl(actual_gui_font_treeview_desc) $desc
set vTcl(actual_gui_font_treeview_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(pr,menufgcolor) #000000
set vTcl(pr,menubgcolor) #d9d9d9
set vTcl(pr,menuanalogcolor) #ececec
set vTcl(pr,treehighlight) firebrick
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Absolute
}




proc vTclWindow.top43 {base} {
    global vTcl
    if {$base == ""} {
        set base .top43
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1270x799+330+4
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1050
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "Greg's Cookbook v3"
    vTcl:DefineAlias "$top" "formCookbookMain" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    ttk::style configure Frame -background $vTcl(actual_gui_bg)
    ttk::style configure Frame -foreground $vTcl(actual_gui_fg)
    ttk::style configure Frame -font "$vTcl(actual_gui_font_dft_desc)"
    frame $top.fra44 \
        -borderwidth 3 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 50 -highlightcolor black -width 1265 
    vTcl:DefineAlias "$top.fra44" "frameToolbar" vTcl:WidgetProc "formCookbookMain" 1
    set site_3_0 $top.fra44
    button $site_3_0.but48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnExit \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Exit 
    vTcl:DefineAlias "$site_3_0.but48" "btnExit" vTcl:WidgetProc "formCookbookMain" 1
    button $site_3_0.but43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnAdd \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but43" "btnAdd" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but43 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Add a new recipe}
    }
    button $site_3_0.but44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnDelete \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but44" "btnDelete" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but44 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Delete the current recipe}
    }
    button $site_3_0.but45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnEdit \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but45" "btnEdit" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but45 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Edit the current recipe}
    }
    button $site_3_0.but46 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnScrape \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but46" "btnScrape" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but46 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Scrape a web page}
    }
    button $site_3_0.but47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnPrint \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but47" "btnPrint" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but47 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Print the current recipe}
    }
    button $site_3_0.but49 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnUtils \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but49" "btnUtils" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but49 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Database Utilities}
    }
    button $site_3_0.but50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -command on_btnConfig \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -text Button 
    vTcl:DefineAlias "$site_3_0.but50" "btnConfig" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_3_0.but50 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Program Configuration}
    }
    place $site_3_0.but48 \
        -in $site_3_0 -x 1210 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but43 \
        -in $site_3_0 -x 120 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but44 \
        -in $site_3_0 -x 170 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but45 \
        -in $site_3_0 -x 241 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but46 \
        -in $site_3_0 -x 504 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but47 \
        -in $site_3_0 -x 630 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 766 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but50 \
        -in $site_3_0 -x 882 -y 5 -width 38 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra45 \
        -borderwidth 3 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 50 -highlightcolor black -width 1265 
    vTcl:DefineAlias "$top.fra45" "frameStatus" vTcl:WidgetProc "formCookbookMain" 1
    set site_3_0 $top.fra45
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label \
        -textvariable TimeDisp 
    vTcl:DefineAlias "$site_3_0.lab44" "lblTimeDisplay" vTcl:WidgetProc "formCookbookMain" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 1170 -y 10 -width 86 -relwidth 0 -height 26 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra46 \
        -borderwidth 3 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 705 -highlightcolor black -width 351 
    vTcl:DefineAlias "$top.fra46" "frameNavigate" vTcl:WidgetProc "formCookbookMain" 1
    set site_3_0 $top.fra46
    frame $site_3_0.fra49 \
        -borderwidth 2 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 198 -highlightcolor black -width 347 
    vTcl:DefineAlias "$site_3_0.fra49" "Frame2" vTcl:WidgetProc "formCookbookMain" 1
    set site_4_0 $site_3_0.fra49
    label $site_4_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Search: 
    vTcl:DefineAlias "$site_4_0.lab54" "Label1" vTcl:WidgetProc "formCookbookMain" 1
    radiobutton $site_4_0.rad43 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text Title -value 0 
    vTcl:DefineAlias "$site_4_0.rad43" "rbTitle" vTcl:WidgetProc "formCookbookMain" 1
    radiobutton $site_4_0.rad44 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text Category -value 2 
    vTcl:DefineAlias "$site_4_0.rad44" "rbCategories" vTcl:WidgetProc "formCookbookMain" 1
    radiobutton $site_4_0.rad45 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_rbClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -text Ingredients -value 1 
    vTcl:DefineAlias "$site_4_0.rad45" "rbIngredients" vTcl:WidgetProc "formCookbookMain" 1
    checkbutton $site_4_0.che46 \
        -activebackground #f9f9f9 -activeforeground black -anchor w \
        -background $vTcl(actual_gui_bg) -command on_chkClick \
        -font TkDefaultFont -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black -justify left -state disabled -text {Show All} \
        -variable che46 
    vTcl:DefineAlias "$site_4_0.che46" "Checkbutton1" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_4_0.che46 <<SetBalloon>> {
        set ::vTcl::balloon::%W {Show Deleted Records as well}
    }
    entry $site_4_0.ent47 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -insertbackground black -selectbackground #c4c4c4 \
        -selectforeground black -state disabled -textvariable EntryText \
        -width 238 
    vTcl:DefineAlias "$site_4_0.ent47" "Entry1" vTcl:WidgetProc "formCookbookMain" 1
    bind $site_4_0.ent47 <KeyRelease> {
        lambda e: on_Entry_Return(e)
    }
    place $site_4_0.lab54 \
        -in $site_4_0 -x 20 -y 20 -width 81 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad43 \
        -in $site_4_0 -x 40 -y 60 -width 92 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad44 \
        -in $site_4_0 -x 40 -y 90 -width 112 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.rad45 \
        -in $site_4_0 -x 40 -y 120 -width 138 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.che46 \
        -in $site_4_0 -x 220 -y 40 -width 113 -relwidth 0 -height 19 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent47 \
        -in $site_4_0 -x 40 -y 150 -width 238 -relwidth 0 -height 29 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra50 \
        -borderwidth 2 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 545 -highlightcolor black -width 345 
    vTcl:DefineAlias "$site_3_0.fra50" "Frame3" vTcl:WidgetProc "formCookbookMain" 1
    set site_4_0 $site_3_0.fra50
    ttk::style configure Treeview \
         -font  "$vTcl(actual_gui_font_treeview_desc)"
    vTcl::widgets::ttk::scrolledtreeview::CreateCmd $site_4_0.scr51 \
        -background $vTcl(actual_gui_bg) -height 15 -highlightcolor black \
        -width 30 
    vTcl:DefineAlias "$site_4_0.scr51" "Scrolledtreeview1" vTcl:WidgetProc "formCookbookMain" 1

    .top43.fra46.fra50.scr51.01 configure -columns Col1 \
        -height 4
        .top43.fra46.fra50.scr51.01 configure -columns {Col1}
        .top43.fra46.fra50.scr51.01 heading #0 -text {Tree}
        .top43.fra46.fra50.scr51.01 heading #0 -anchor center
        .top43.fra46.fra50.scr51.01 column #0 -width 165
        .top43.fra46.fra50.scr51.01 column #0 -minwidth 20
        .top43.fra46.fra50.scr51.01 column #0 -stretch 1
        .top43.fra46.fra50.scr51.01 column #0 -anchor w
        .top43.fra46.fra50.scr51.01 heading Col1 -text {Col1}
        .top43.fra46.fra50.scr51.01 heading Col1 -anchor center
        .top43.fra46.fra50.scr51.01 column Col1 -width 166
        .top43.fra46.fra50.scr51.01 column Col1 -minwidth 20
        .top43.fra46.fra50.scr51.01 column Col1 -stretch 1
        .top43.fra46.fra50.scr51.01 column Col1 -anchor w
    place $site_4_0.scr51 \
        -in $site_4_0 -x 0 -y 0 -width 345 -relwidth 0 -height 503 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra49 \
        -in $site_3_0 -x 0 -y 507 -width 347 -relwidth 0 -height 198 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra50 \
        -in $site_3_0 -x 0 -y 0 -width 347 -relwidth 0 -height 505 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra47 \
        -borderwidth 3 -relief ridge -background $vTcl(actual_gui_bg) \
        -height 755 -highlightcolor black -width 915 
    vTcl:DefineAlias "$top.fra47" "Frame1" vTcl:WidgetProc "formCookbookMain" 1
    set site_3_0 $top.fra47
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr52 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr52" "Scrolledtext1" vTcl:WidgetProc "formCookbookMain" 1

    $site_3_0.scr52.01 configure -background white \
        -font font9 \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap word
    vTcl::widgets::ttk::scrolledlistbox::CreateCmd $site_3_0.scr53 \
        -background $vTcl(actual_gui_bg) -height 75 -highlightcolor black \
        -width 125 
    vTcl:DefineAlias "$site_3_0.scr53" "Scrolledlistbox1" vTcl:WidgetProc "formCookbookMain" 1

    $site_3_0.scr53.01 configure -background white \
        -cursor xterm \
        -font font10 \
        -foreground black \
        -height 3 \
        -highlightcolor #d9d9d9 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10
    label $site_3_0.lab43 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 12 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief ridge \
        -text Label -textvariable RecipeTitle 
    vTcl:DefineAlias "$site_3_0.lab43" "lblTitle" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab44 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -borderwidth 2 -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief ridge \
        -text Label-Image 
    vTcl:DefineAlias "$site_3_0.lab44" "lblImage" vTcl:WidgetProc "formCookbookMain" 1
    message $site_3_0.mes43 \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief ridge \
        -text Message -textvariable RecipeCategories -width 805 
    vTcl:DefineAlias "$site_3_0.mes43" "msgCategories" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab47 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Label \
        -textvariable IdLableShow 
    vTcl:DefineAlias "$site_3_0.lab47" "lblID" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Ubuntu} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Source: 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab49 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Ubuntu} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Servings: 
    vTcl:DefineAlias "$site_3_0.lab49" "Label3" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab50 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Ubuntu} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text Description: 
    vTcl:DefineAlias "$site_3_0.lab50" "Label4" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab51 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief ridge \
        -text Label -textvariable RecipeTotalTime 
    vTcl:DefineAlias "$site_3_0.lab51" "lblTotalTime" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab52 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Ubuntu} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Total Time:} 
    vTcl:DefineAlias "$site_3_0.lab52" "Label5" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab53 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Ubuntu} -size 11 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief ridge \
        -text Label -textvariable RecipeRating 
    vTcl:DefineAlias "$site_3_0.lab53" "Label6" vTcl:WidgetProc "formCookbookMain" 1
    label $site_3_0.lab54 \
        -activebackground #f9f9f9 -activeforeground black -anchor e \
        -background $vTcl(actual_gui_bg) \
        -font {-family {Ubuntu} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -text Rating: 
    vTcl:DefineAlias "$site_3_0.lab54" "Label7" vTcl:WidgetProc "formCookbookMain" 1
    vTcl::widgets::ttk::scrolledtext::CreateCmd $site_3_0.scr43 \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 75 -highlightcolor black -width 125 
    vTcl:DefineAlias "$site_3_0.scr43" "stNotes" vTcl:WidgetProc "formCookbookMain" 1

    $site_3_0.scr43.01 configure -background white \
        -font font12 \
        -foreground black \
        -height 3 \
        -highlightcolor black \
        -insertbackground black \
        -insertborderwidth 3 \
        -selectbackground #c4c4c4 \
        -selectforeground black \
        -width 10 \
        -wrap word
    message $site_3_0.mes44 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable RecipeServings -width 465 
    vTcl:DefineAlias "$site_3_0.mes44" "lblServings" vTcl:WidgetProc "formCookbookMain" 1
    message $site_3_0.mes45 \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black -relief sunken \
        -text Label -textvariable RecipeSource -width 465 
    vTcl:DefineAlias "$site_3_0.mes45" "lblSource" vTcl:WidgetProc "formCookbookMain" 1
    place $site_3_0.scr52 \
        -in $site_3_0 -x 404 -y 377 -width 512 -relwidth 0 -height 317 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr53 \
        -in $site_3_0 -x 10 -y 377 -width 385 -relwidth 0 -height 317 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 20 -y 8 -width 568 -relwidth 0 -height 36 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 602 -y 18 -width 302 -relwidth 0 -height 275 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes43 \
        -in $site_3_0 -x 90 -y 321 -width 807 -relwidth 0 -height 40 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 20 -y 331 -width 46 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 23 -y 65 -width 86 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 33 -y 102 -width 76 -relwidth 0 -height 17 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 30 -y 193 -width 83 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 119 -y 128 -width 468 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab52 \
        -in $site_3_0 -x 20 -y 133 -width 89 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab53 \
        -in $site_3_0 -x 120 -y 158 -width 468 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 30 -y 163 -width 79 -relwidth 0 -height 18 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.scr43 \
        -in $site_3_0 -x 120 -y 188 -width 470 -relwidth 0 -height 129 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes44 \
        -in $site_3_0 -x 120 -y 97 -width 467 -relwidth 0 -height 28 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.mes45 \
        -in $site_3_0 -x 120 -y 49 -width 467 -relwidth 0 -height 46 \
        -relheight 0 -anchor nw -bordermode ignore 
    vTcl:copy_lock $top.fra47
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra44 \
        -in $top -x 0 -y 0 -width 1266 -relwidth 0 -height 46 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra45 \
        -in $top -x 1 -y 750 -width 1266 -relwidth 0 -height 46 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra46 \
        -in $top -x 0 -y 45 -width 351 -relwidth 0 -height 705 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra47 \
        -in $top -x 351 -y 47 -width 917 -relwidth 0 -height 695 -relheight 0 \
        -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top43 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

